from __future__ import annotations
from dataclasses import dataclass

@dataclass
class ServiceHint:
    service:str; what:str; risk:str; why:str; check:str; learn:str

RISK_COLORS:dict[str,dict[str,str]] = {
    "INFO":    {"bg":"#e8f4fd","border":"#1a7abf","text":"#0d4a7a","badge":"#1a7abf"},
    "LOW":     {"bg":"#eafaf1","border":"#1e8449","text":"#145a32","badge":"#1e8449"},
    "MEDIUM":  {"bg":"#fef9e7","border":"#d4ac0d","text":"#7d6608","badge":"#d4ac0d"},
    "HIGH":    {"bg":"#fef5e7","border":"#d35400","text":"#784212","badge":"#d35400"},
    "CRITICAL":{"bg":"#fdedec","border":"#c0392b","text":"#78281f","badge":"#c0392b"},
}
RISK_ICONS:dict[str,str] = {
    "INFO":"&#9432;","LOW":"&#10003;","MEDIUM":"&#9888;","HIGH":"&#9888;","CRITICAL":"&#128683;",
}

HINTS:dict[int,ServiceHint] = {
    22:ServiceHint("SSH (Secure Shell)","SSH allows encrypted remote command-line access to a machine. Used by administrators to manage servers remotely.","LOW","SSH is secure by design, but weak passwords or old versions invite brute-force attacks. SSH v1 is obsolete and broken.","Verify SSH v2 is enforced, root login is disabled, and password auth is replaced with SSH key authentication.","Best practice: disable password login, use SSH keys only, restrict access by IP."),
    23:ServiceHint("Telnet","Telnet provides remote terminal access but sends everything including passwords in plain text with no encryption.","CRITICAL","Anyone on the same network can intercept login credentials with a packet sniffer. Telnet has been obsolete since SSH was introduced in 1995.","This service should almost never be open. If it is, replace it with SSH immediately.","Telnet is dangerous — SSH does everything Telnet does, securely."),
    21:ServiceHint("FTP (File Transfer Protocol)","An old file transfer protocol that sends everything including passwords in plain text.","HIGH","FTP credentials are sent unencrypted. Anonymous FTP can expose entire file systems to anyone.","Check if anonymous login is enabled. Replace with SFTP (port 22) where possible.","Never use plain FTP. Use SFTP (port 22) or FTPS (port 990) instead."),
    25:ServiceHint("SMTP (Email Server)","The protocol used to send emails between mail servers.","MEDIUM","An open SMTP relay will be abused to send spam within hours, getting your IP blacklisted globally.","Verify the server is NOT an open relay. Test at mxtoolbox.com.","Open email relays are spam engines. Test yours immediately."),
    53:ServiceHint("DNS (Domain Name System)","DNS translates domain names into IP addresses — the phone book of the internet.","MEDIUM","An open DNS resolver can be abused for DNS amplification DDoS attacks. Zone transfers can expose internal network maps.","Verify DNS does not allow open recursive queries. Disable zone transfers to unauthorized servers.","Open DNS resolvers are abused for DDoS amplification attacks."),
    69:ServiceHint("TFTP (Trivial FTP)","Extremely simple file transfer with NO authentication at all.","CRITICAL","TFTP has zero authentication — anyone can read and write files. Should only exist on network equipment in isolated environments.","If found on a general server, disable it immediately.","TFTP with no auth = anyone can read/write files on the server."),
    80:ServiceHint("HTTP (Web Server)","The standard unencrypted web protocol. Your web server is accepting connections.","MEDIUM","HTTP transmits all data in plain text. Login forms and cookies are visible to interceptors.","Check if HTTPS (443) is available and redirect HTTP to it. Note the server version for CVEs.","HTTP should redirect to HTTPS. Plain HTTP alone is not acceptable for sensitive data."),
    110:ServiceHint("POP3 (Email Retrieval)","POP3 lets email clients download emails from a server. Older protocol — IMAP is the modern replacement.","MEDIUM","Plain POP3 sends credentials in plain text. POP3S (port 995) encrypts with TLS.","Ensure clients use POP3S (995) not plain POP3 (110).","Always use POP3S (995) or IMAPS (993), never plain."),
    111:ServiceHint("RPCbind / Portmapper","RPCbind maps RPC program numbers to ports — a directory service for RPC-based services.","HIGH","RPCbind reveals every RPC service on the machine. Attackers query it to find NFS and other targets.","Disable RPCbind if NFS is not needed. Firewall port 111 from external access.","Port 111 is an attacker's roadmap to every RPC service."),
    135:ServiceHint("MS-RPC (Windows RPC)","Windows Remote Procedure Call — internal Windows service communication.","HIGH","Exposed RPC has been the vector for major Windows worms (Blaster, Sasser). Should not be publicly accessible.","Firewall port 135 from the internet. No reason for this to be public.","RPC exposed to the internet caused several major Windows worms."),
    137:ServiceHint("NetBIOS Name Service","NetBIOS name resolution service — legacy Windows networking.","HIGH","NetBIOS exposes computer names and workgroup details. Attack surface for enumeration.","Disable NetBIOS on modern Windows networks. Firewall 137-139 from external access.","NetBIOS is legacy — disable it in favor of DNS."),
    139:ServiceHint("NetBIOS Session Service","Older Windows file/printer sharing, predecessor to SMB.","HIGH","NetBIOS exposes network information including computer names and workgroup details.","Disable on modern networks. Firewall ports 137-139 from external access.","NetBIOS is legacy and should be disabled in favor of DNS."),
    143:ServiceHint("IMAP (Email Access)","IMAP lets email clients access emails on the server. Multi-device capable.","MEDIUM","Plain IMAP on port 143 is unencrypted. IMAPS (993) is the encrypted version.","Verify clients use IMAPS (993) not plain IMAP (143).","IMAPS (993) = encrypted. Plain IMAP (143) = credentials in plain text."),
    161:ServiceHint("SNMP (Network Management)","Used to monitor and manage network devices. Can expose detailed device config.","HIGH","SNMP v1/v2 default community strings 'public'/'private' allow anyone to read or modify device settings.","Change default community strings immediately. Upgrade to SNMPv3. Firewall from external access.","Default SNMP community strings expose full device configuration."),
    443:ServiceHint("HTTPS (Encrypted Web Server)","The encrypted version of HTTP — all data encrypted using TLS.","INFO","HTTPS itself is secure. Risks come from weak TLS config, expired certs, or vulnerable web apps.","Verify TLS 1.2 or 1.3 only. Check certificate expiry. Test with SSL Labs (ssllabs.com).","HTTPS is correct — now check the web application behind it."),
    445:ServiceHint("SMB (Windows File Sharing)","Windows file and printer sharing protocol — backbone of Windows networking.","CRITICAL","EternalBlue (WannaCry, 2017) and NotPetya spread via SMB. NEVER expose port 445 to the internet.","Firewall from the internet — no exceptions. Verify SMB signing enabled. Apply MS17-010 patch.","WannaCry spread via this exact port. Firewall it from the internet immediately."),
    512:ServiceHint("rexec (Remote Execution)","1980s Unix service for executing commands remotely. Sends credentials in plain text.","CRITICAL","rexec transmits credentials in plain text with NO encryption. Often requires no authentication on legacy systems.","This service should not exist on any modern system. Disable it immediately. Replace with SSH.","rexec is a 1980s relic. Disable it and use SSH."),
    513:ServiceHint("rlogin (Remote Login)","Remote terminal access to Unix systems. Sends everything in plain text.","CRITICAL","rlogin .rhosts trust can allow passwordless login from any host. Classic Metasploitable exploitation path.","Disable rlogin. Delete .rhosts and /etc/hosts.equiv files. Replace with SSH.","rlogin with .rhosts trust = passwordless remote access for attackers."),
    514:ServiceHint("rsh (Remote Shell) / Syslog","TCP 514 = rsh (Remote Shell). UDP 514 = Syslog. rsh allows passwordless command execution.","CRITICAL","rsh has same .rhosts trust as rlogin. With rlogin (513) and rexec (512) — the classic r-services exploitation trio.","Disable all r-services. Remove .rhosts and /etc/hosts.equiv files.","rsh + rlogin + rexec = the classic Metasploitable exploitation trio."),
    902:ServiceHint("VMware ESXi/vCenter","VMware hypervisor management port.","HIGH","ESXiArgs ransomware (2023) encrypted thousands of VMs via exposed VMware ports.","VMware management interfaces should be on isolated management networks, not the internet.","ESXiArgs (2023) encrypted thousands of VMs via exposed VMware ports."),
    993:ServiceHint("IMAPS (Encrypted Email)","Encrypted IMAP over TLS. This is the correct, secure version.","INFO","IMAPS itself is secure. Check TLS version and certificate validity.","Verify TLS 1.2 or 1.3 is used. Check certificate expiry.","IMAPS is correct — same TLS checks as HTTPS apply."),
    995:ServiceHint("POP3S (Encrypted Email)","Encrypted POP3 over TLS. This is the correct, secure version.","INFO","POP3S itself is secure. Check TLS version and certificate validity.","Verify TLS 1.2 or 1.3. Check certificate expiry.","POP3S is correct — same TLS checks as HTTPS apply."),
    1099:ServiceHint("Java RMI Registry","Java Remote Method Invocation — allows Java programs to call remote methods.","CRITICAL","Java RMI deserialization vulnerabilities allow remote code execution. Well-known attack vector in penetration testing.","Disable if not needed. Restrict by IP firewall. Ensure Java is fully patched.","Java RMI on Metasploitable is directly exploitable for remote code execution."),
    1433:ServiceHint("Microsoft SQL Server","Microsoft's enterprise database system.","CRITICAL","MSSQL exposed to the internet is constantly attacked. SA account with weak password is the most common entry point.","Firewall this port. Disable SA account or use strong password. Disable xp_cmdshell if enabled.","SQL Server with SA and a weak password = complete server compromise."),
    1521:ServiceHint("Oracle Database","Oracle's enterprise database platform — common in large corporations.","CRITICAL","Oracle databases contain sensitive enterprise data. Check for default accounts (SCOTT/TIGER, SYS/CHANGE_ON_INSTALL).","Verify this is intentionally exposed. Change all default accounts immediately.","Oracle default accounts are well-documented — change them immediately."),
    2049:ServiceHint("NFS (Network File System)","Allows a server to share directories and files over the network.","HIGH","Misconfigured NFS exports allow anyone to mount and read/write the filesystem. Metasploitable exports /root by default.","Run 'showmount -e <target>' to see exports. Check /etc/exports — no entry should have '*'.","'showmount -e <ip>' reveals exported shares. World-readable NFS = full filesystem access."),
    2375:ServiceHint("Docker API (Unencrypted)","Docker's management API without TLS — controls all containers.","CRITICAL","Exposed Docker API gives complete host control. Exploited by cryptomining malware and ransomware.","Port 2375 should NEVER be publicly accessible. Use 2376 (TLS) instead.","Exposed Docker API = full host compromise."),
    2376:ServiceHint("Docker API (TLS)","Docker's management API with TLS encryption.","HIGH","Even with TLS, this gives full Docker control. Misconfigured TLS or leaked certs are a serious risk.","Verify TLS client authentication enforced. Restrict to authorized admin machines.","Docker API even with TLS should be restricted by IP or VPN."),
    3000:ServiceHint("Grafana / Dev Server","Port 3000 commonly used by Grafana monitoring and development servers.","HIGH","Grafana had critical auth bypass (CVE-2021-43798). Dev servers often have no auth and expose debug info.","Identify what is running. If Grafana, ensure patched and authenticated. Dev servers should not be public.","Grafana path traversal (2021) let attackers read any file on the server."),
    3306:ServiceHint("MySQL Database","One of the most popular database systems. Stores structured data for applications.","CRITICAL","A database exposed to the internet is a critical finding. Databases should NEVER be publicly accessible.","Verify firewall rules immediately. Check if root login from any host is allowed.","Databases must be firewalled. Only your application server should connect."),
    3389:ServiceHint("RDP (Remote Desktop)","Microsoft's graphical remote access protocol for Windows.","HIGH","RDP is constantly attacked. BlueKeep (CVE-2019-0708) allows unauthenticated RCE. Ransomware targets open RDP.","RDP should never be directly on the internet. Use a VPN. Enable NLA. Keep Windows patched.","If you need remote Windows access, always tunnel through a VPN first."),
    5432:ServiceHint("PostgreSQL Database","Advanced open-source relational database.","CRITICAL","A database reachable from the internet is a serious security issue. Data breaches often start here.","Firewall this port immediately if publicly accessible. Review pg_hba.conf for remote connection restrictions.","No database should be directly reachable from the public internet."),
    5900:ServiceHint("VNC (Virtual Network Computing)","Graphical remote desktop system — gives visual control of the target machine.","HIGH","Many VNC deployments have no authentication or weak passwords. Some transmit data unencrypted.","Verify VNC requires a strong password. Check if session is encrypted.","VNC without encryption is as dangerous as Telnet."),
    6379:ServiceHint("Redis (In-Memory Database)","Extremely fast in-memory data store for caching and session management.","CRITICAL","Redis has NO authentication by default and binds to all interfaces. Can leak sessions, tokens, and in some versions allow RCE.","Check if authentication is required (requirepass in redis.conf). Redis should only listen on 127.0.0.1.","Open Redis = instant data breach. Lock it down first."),
    6443:ServiceHint("Kubernetes API Server","Control plane for Kubernetes — manages all containers across a cluster.","CRITICAL","Exposed Kubernetes API is a top target for cryptomining. Misconfigured RBAC can allow anonymous access.","Verify authentication and RBAC are properly configured. API server should not be publicly accessible.","Open Kubernetes API = full cluster compromise."),
    6667:ServiceHint("IRC (Internet Relay Chat)","Real-time chat protocol. Finding IRC on a server unexpectedly is unusual.","MEDIUM","Malware and botnets use IRC for command-and-control. UnrealIRCd on Metasploitable has a hardcoded backdoor (CVE-2010-2075).","If not an intentional IRC server, investigate immediately — may indicate malware.","UnrealIRCd 3.2.8.1 has a hardcoded backdoor — instantly exploitable."),
    8080:ServiceHint("HTTP Alternate Port","Secondary web port for dev servers, proxies, or admin panels. Often no encryption.","MEDIUM","Dev or admin tools accidentally left exposed with weaker authentication.","Identify what application is running. Check if intended to be publicly accessible.","Dev servers and admin panels on 8080 are a common source of data exposure."),
    8443:ServiceHint("HTTPS Alternate Port","Alternative HTTPS port for admin panels, APIs, or secondary web services.","LOW","May expose admin interfaces not meant to be publicly accessible.","Identify the application. Verify it requires authentication.","Same security checks as port 443 apply here."),
    9200:ServiceHint("Elasticsearch","Search and analytics engine — often stores large amounts of sensitive data.","CRITICAL","No authentication by default until version 8.0 (2022). Billions of records were exposed through open clusters.","Check if X-Pack security/authentication is enabled. Should not be publicly accessible without auth.","Pre-8.0 Elasticsearch with no config = all data is public."),
    10000:ServiceHint("Webmin Admin Panel","Web-based system administration interface for Unix/Linux.","HIGH","Webmin has had critical CVEs including CVE-2019-15107 (unauthenticated RCE). Admin panels on the internet are prime targets.","Should not be publicly accessible. Use a VPN or SSH tunnel. Verify version and apply patches.","Admin panels on the internet are prime targets — put them behind a VPN."),
    11211:ServiceHint("Memcached","Distributed caching system — stores data in memory to speed up applications.","CRITICAL","NO authentication by default. Used for the largest DDoS attack ever recorded (1.7 Tbps, 2018). Binds to 0.0.0.0 by default.","Must only listen on localhost. If externally accessible, firewall it and restart bound to 127.0.0.1.","Memcached: no auth, DDoS amplification, binds to 0.0.0.0 by default."),
    27017:ServiceHint("MongoDB","Popular NoSQL database storing JSON-like documents.","CRITICAL","No authentication by default until version 8.0. Hundreds of thousands of exposed databases were wiped and held for ransom (2017-2019).","Verify authentication is enabled. Check mongod.conf bindIp — should NOT be 0.0.0.0.","MongoDB with no auth and no firewall = all your data is public."),
}

def get_hint(port:int)->ServiceHint|None: return HINTS.get(port)
def get_risk(port:int)->str: h=HINTS.get(port); return h.risk if h else "INFO"
def risk_sort_key(risk:str)->int: return {"INFO":0,"LOW":1,"MEDIUM":2,"HIGH":3,"CRITICAL":4}.get(risk,0)
